engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - python:

ratings:
  paths:
  - app/**

exclude_paths:
- migrations/**/*
