language: 
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install pytest-cov
- pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
- python -m pytest tests/

after_success:
- coverage report
- coveralls




