language: 
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install pytest-cov
- pip install -r requirements.txt

script:
- py.test --cov=app app/tests/

after_success:
- coverage report
- coveralls
