language:
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install pytest-cov
- pip install -r requirements.txt

services:
- postgresql

before_script:
- psql -c 'create database shoppinglist;' -U postgres

script:
- python -m pytest --cov tests

after_success:
- coverage report
- coveralls
