language: 
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt

script:
- python tests/test_auth.py
- python tests/test_api.py

after_success:
- coverage report
- coveralls
