language:
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install pytest-cov
- pip install -r requirements.txt

services:
- postgresql

before_script:
- psql -c "create database test_db;" -U arthuroe
- psql -c "ALTER USER arthuroe PASSWORD 'dbadmin';" -U arthuroe

script:
- python -m pytest tests/

after_success:
- coverage report
- coveralls
