# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          TEST_DATABASE_URL: postgres://ubuntu@localhost:5432/shoppinglist?=sslmode=disable

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image:  circleci/postgres:9.6
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: shoppinglist
          POSTGRES_PASSWORD: ""
    working_directory: ~/ShoppingList_API

    steps:
      - checkout
      - run:
          name: install testing dependencies
          command: |
            sudo pip install coverage
            sudo pip install coveralls
            sudo pip install pytest-cov
            sudo pip install -r requirements.txt

      - run:
          name: install psql
          command: |
            sudo apt-get update && sudo apt-get install -y postgresql-client

      - run:
          name: start postgres
          command: |
            sudo service postgresql start

      - run:
          name: create psql user
          command: |
            sudo psql -c "CREATE ROLE arthuroe PASSWORD 'dbadmin' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
            sudo sql -c "create database shoppinglist;" -U postgres

      # run tests!
      - run:
          name: run tests
          command: |
            python -m pytest --cov tests
      # report test data
      - run:
          name: send coverage data to coveralls
          command: |
            coveralls

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
