# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://postgres@localhost/shoppinglist?sslmode=disable
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: shoppinglist
          POSTGRES_PASSWORD: ""

    working_directory: ~/ShoppingList_API

    steps:
      - checkout

      - run:
          name: install testing dependencies
          command: |
            sudo pip install coverage
            sudo pip install coveralls
            sudo pip install pytest-cov
            sudo pip install -r requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            python -m pytest --cov tests 

      # report test data
      - run:
          name: send coverage data to coveralls
          command: |
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports
